version: "{branch} {build}"

build:
  verbosity: detailed
  
install:
  - appveyor DownloadFile https://dl.google.com/dl/cloudsdk/channels/rapid/GoogleCloudSDKInstaller.exe
  - GoogleCloudSDKInstaller.exe /S /noreporting /nostartmenu /nodesktop /logtofile /D=C:\cloudsdk

build_script:
  - gcloud help

test: off
